package co.com.codesa.clienteposslimgiros.enumeraciones;

public enum EnumVariablesImpresion{
	
	//General
	TITULO_IMPRESION("TITULO_IMPRESION"),
	TIPO_REIMPRESION("TIPO_REIMPRESION"),
	FECHA_SISTEMA("FECHA_SISTEMA"),
	
	//Transaccion
	NUMERO_FACTURA("NUMERO_FACTURA"),
	PIN_GIRO("PIN_GIRO"),
	VALOR_ENVIO_GIRO("VALOR_ENVIO_GIRO"),
	VALOR_FLETE("VALOR_FLETE"),
	VALOR_PAGO("VALOR_PAGO"),
	VALOR_ENTREGADO("VALOR_ENTREGADO"),
	FECHA_TRANSACCION("FECHA_TRANSACCION"),
	FECHA_ENVIO("FECHA_ENVIO"),
	NOTAS("NOTAS"),
	CONCEPTOS("CONCEPTOS"),
	MEDIOS_PAGO("MEDIOS_PAGO"),
	TOTAL_MEDIOS_PAGO("TOTAL_MEDIOS_PAGO"),
	NOMBRE_CAJERO("NOMBRE_CAJERO"),
	REFERENCIA("REFERENCIA"),
	EXISTE_POLITICA("EXISTE_POLITICA"),
	
	//Medio Entrega (FISICO ó ELECTRONICO)
	MEDIO_ENTREGA("MEDIO_ENTREGA"),
	CORREO_TERCERO_ORIGEN("CORREO_TERCERO_ORIGEN"),
	CORREO_TERCERO_DESTINO("CORREO_TERCERO_DESTINO"),
	CORREO_TERCERO_NUEVO("CORREO_TERCERO_NUEVO"),
	
	//Promociones
	PROMOCIONES("PROMOCIONES"),
	EXISTE_PROMOCIONES("EXISTE_PROMOCIONES"),
	
	//Concepto
	DESCRIPCION_CONCEPTO("DESCRIPCION_CONCEPTO"),
	VALOR_CONCEPTO("VALOR_CONCEPTO"),
	
	//Documento
	ABREVIATURA_DOCUMENTO("ABREVIATURA_DOCUMENTO"),
	INICIO_DOCUMENTO("INICIO_DOCUMENTO"),
	FIN_DOCUMENTO("FIN_DOCUMENTO"),
	RESOLUCION_DOCUMENTO("RESOLUCION_DOCUMENTO"),
	DOCUMENTO_AUXILIAR("DOCUMENTO_AUXILIAR"),
	
	//Representante comercial
	NOMBRE_REPRESENTANTE_COMERCIAL_EMPRESA("NOMBRE_REPRESENTANTE_COMERCIAL_EMPRESA"),
	NIT_REPRESENTANTE_COMERCIAL_EMPRESA("NIT_REPRESENTANTE_COMERCIAL_EMPRESA"),
	TELEFONO_REPRESENTANTE_COMERCIAL_EMPRESA("TELEFONO_REPRESENTANTE_COMERCIAL_EMPRESA"),
	
	//Empresa
	NOMBRE_EMPRESA("NOMBRE_EMPRESA"),
	NIT_EMPRESA("NIT_EMPRESA"),
	PAGINA_WEB_EMPRESA("PAGINA_WEB_EMPRESA"),
	TELEFONO_EMPRESA("TELEFONO_EMPRESA"),
	CORREO_ELECTRONICO_EMPRESA("CORREO_ELECTRONICO_EMPRESA"),
	DIRECCION_EMPRESA("DIRECCION_EMPRESA"),
	
	//Agencia
	NOMBRE_AGENCIA("NOMBRE_AGENCIA"),
	DIRECCION_AGENCIA("DIRECCION_AGENCIA"),
	TELEFONO_AGENCIA("TELEFONO_AGENCIA"),
	TERRITORIO_MUNICIPIO_AGENCIA("TERRITORIO_MUNICIPIO_AGENCIA"),
	//Origen
	NOMBRE_AGENCIA_ORIGEN("NOMBRE_AGENCIA_ORIGEN"),
	DIRECCION_AGENCIA_ORIGEN("DIRECCION_AGENCIA_ORIGEN"),
	TELEFONO_AGENCIA_ORIGEN("TELEFONO_AGENCIA_ORIGEN"),
	TERRITORIO_MUNICIPIO_AGENCIA_ORIGEN("TERRITORIO_MUNICIPIO_AGENCIA_ORIGEN"),
	//Destino
	NOMBRE_AGENCIA_DESTINO("NOMBRE_AGENCIA_DESTINO"),
	DIRECCION_AGENCIA_DESTINO("DIRECCION_AGENCIA_DESTINO"),
	TELEFONO_AGENCIA_DESTINO("TELEFONO_AGENCIA_DESTINO"),
	TERRITORIO_MUNICIPIO_AGENCIA_DESTINO("TERRITORIO_MUNICIPIO_AGENCIA_DESTINO"),
	
	//Caja
	CODIGO_CAJA("CODIGO_CAJA"),
	DESCRIPCION_CAJA("DESCRIPCION_CAJA"),
	FECHA_APERTURA_CAJA("FECHA_APERTURA_CAJA"),
	FECHA_CIERRE_CAJA("FECHA_CIERRE_CAJA"),
	//Origen
	CODIGO_CAJA_ORIGEN("CODIGO_CAJA_ORIGEN"),
	//Proceso de Cierre y Arqueo
	SALDO_INICIAL("SALDO_INICIAL"),
	SALDO_FINAL("SALDO_FINAL"),
	TOTAL_INGRESO("TOTAL_INGRESO"),
	TOTAL_EGRESO("TOTAL_EGRESO"),
	TOTAL_SALDOS_CAJA("TOTAL_SALDOS_CAJA"),
	INGRESOS_X_CONCEPTO("INGRESOS_X_CONCEPTO"),
	EGRESOS_X_CONCEPTO("EGRESOS_X_CONCEPTO"),
	INGRESOS_X_DENOMINACION_BILLETES("INGRESOS_X_DENOMINACION_BILLETES"),
	INGRESOS_X_DENOMINACION_MONEDAS("INGRESOS_X_DENOMINACION_MONEDAS"),
	INGRESOS_X_DENOMINACION_CHEQUES("INGRESOS_X_DENOMINACION_CHEQUES"),
	INGRESOS_X_DENOMINACION_VALES("INGRESOS_X_DENOMINACION_VALES"),
	TOTAL_INGRESOS_X_DENOMINACION_BILLETES("TOTAL_INGRESOS_X_DENOMINACION_BILLETES"),
	TOTAL_INGRESOS_X_DENOMINACION_MONEDAS("TOTAL_INGRESOS_X_DENOMINACION_MONEDAS"),
	TOTAL_INGRESOS_X_DENOMINACION_CHEQUES("TOTAL_INGRESOS_X_DENOMINACION_CHEQUES"),
	TOTAL_INGRESOS_X_DENOMINACION_VALES("TOTAL_INGRESOS_X_DENOMINACION_VALES"),
	
	//Tercero
	NOMBRE_TERCERO("NOMBRE_TERCERO"),
	IDENTIFICACION_TERCERO("IDENTIFICACION_TERCERO"),
	DIRECCION_TERCERO("DIRECCION_TERCERO"),
	TELEFONO_TERCERO("TELEFONO_TERCERO"),
	CELULAR_TERCERO("CELULAR_TERCERO"),
	DESCRIPCION_ACTIVIDAD_ECONOMICA_TERCERO("DESCRIPCION_ACTIVIDAD_ECONOMICA_TERCERO"),
	TOTAL_OPERACIONES_DIA_TERCERO("TOTAL_OPERACIONES_DIA_TERCERO"),
	//Origen
	NOMBRE_TERCERO_ORIGEN("NOMBRE_TERCERO_ORIGEN"),
	IDENTIFICACION_TERCERO_ORIGEN("IDENTIFICACION_TERCERO_ORIGEN"),
	TIPO_E_IDENTIFICACION_TERCERO_ORIGEN("TIPO_E_IDENTIFICACION_TERCERO_ORIGEN"),
	DIRECCION_TERCERO_ORIGEN("DIRECCION_TERCERO_ORIGEN"),
	TELEFONO_TERCERO_ORIGEN("TELEFONO_TERCERO_ORIGEN"),
	CELULAR_TERCERO_ORIGEN("CELULAR_TERCERO_ORIGEN"),
	DESCRIPCION_ACTIVIDAD_ECONOMICA_TERCERO_ORIGEN("DESCRIPCION_ACTIVIDAD_ECONOMICA_TERCERO_ORIGEN"),
	//Destino
	NOMBRE_TERCERO_DESTINO("NOMBRE_TERCERO_DESTINO"),
	IDENTIFICACION_TERCERO_DESTINO("IDENTIFICACION_TERCERO_DESTINO"),
	TIPO_E_IDENTIFICACION_TERCERO_DESTINO("TIPO_E_IDENTIFICACION_TERCERO_DESTINO"),
	DIRECCION_TERCERO_DESTINO("DIRECCION_TERCERO_DESTINO"),
	TELEFONO_TERCERO_DESTINO("TELEFONO_TERCERO_DESTINO"),
	CELULAR_TERCERO_DESTINO("CELULAR_TERCERO_DESTINO"),
	//Nuevo: valido para cambio de beneficiario
	NOMBRE_TERCERO_NUEVO("NOMBRE_TERCERO_NUEVO"),
	IDENTIFICACION_TERCERO_NUEVO("IDENTIFICACION_TERCERO_NUEVO"),
	DIRECCION_TERCERO_NUEVO("DIRECCION_TERCERO_NUEVO"),
	TELEFONO_TERCERO_NUEVO("TELEFONO_TERCERO_NUEVO"),
	CELULAR_TERCERO_NUEVO("CELULAR_TERCERO_NUEVO"),
	//Convenio: valido para un proceso de convenio
	NOMBRE_TERCERO_CONVENIO("NOMBRE_TERCERO_CONVENIO"),
	IDENTIFICACION_TERCERO_CONVENIO("IDENTIFICACION_TERCERO_CONVENIO"),
	TELEFONO_TERCERO_CONVENIO("TELEFONO_TERCERO_CONVENIO"),
	CELULAR_TERCERO_CONVENIO("CELULAR_TERCERO_CONVENIO"),
	TIPO_E_IDENTIFICACION_TERCERO_CONVENIO("TIPO_E_IDENTIFICACION_TERCERO_CONVENIO"),
	//Apoderado: valido para una operacion de pago de giro
	NOMBRE_TERCERO_APODERADO("NOMBRE_TERCERO_APODERADO"),
	IDENTIFICACION_TERCERO_APODERADO("IDENTIFICACION_TERCERO_APODERADO"),
	EXISTE_APODERADO("EXISTE_APODERADO"),
	
	//Seguro
	NUMERO_POLIZA("NUMERO_POLIZA"),
	CERTIFICADO_INDIVIDUAL("CERTIFICADO_INDIVIDUAL"),
	NOMBRE_ASEGURADORA("NOMBRE_ASEGURADORA"),
	NIT_ASEGURADORA("NIT_ASEGURADORA"),
	NOMBRE_TOMADOR("NOMBRE_TOMADOR"),
	NIT_TOMADOR("NIT_TOMADOR"),
	NOMBRE_ASEGURADO("NOMBRE_ASEGURADO"),
	IDENTIFICACION_ASEGURADO("IDENTIFICACION_ASEGURADO"),
	VALOR_PRIMA("VALOR_PRIMA"),
	VALOR_ASEGURADO_HURTO("VALOR_ASEGURADO_HURTO"),
	VALOR_TOTAL_FACTURA_SEGURO("VALOR_TOTAL_FACTURA_SEGURO"),
	VALOR_ASEGURADO_ACCIDENTE("VALOR_ASEGURADO_ACCIDENTE"),
	TELEFONOS_NACIONAL("TELEFONOS_NACIONAL"),
	TELEFONOS_CALI("TELEFONOS_CALI"),
	TELEFONOS_CELULARES("TELEFONOS_CELULARES"),
	VALOR_SMS("VALOR_SMS"),
	
	//SMS
	NOMBRE_PROVEEDOR("NOMBRE_PROVEEDOR"),
	NIT_PROVEEDOR("NIT_PROVEEDOR"),
	DIRECCION_PROVEEDOR("DIRECCION_PROVEEDOR"),
	TELEFONO_PROVEEDOR("TELEFONO_PROVEEDOR"),
	IVA_SMS("IVA_SMS"),
	TOTAL_SMS("TOTAL_SMS"),
	PIN_SMS("PIN_SMS"),
	
	//Recaudo
	PIN_RECAUDO("PIN_RECAUDO"),
	CODIGO_EXTERNO_RECAUDO("CODIGO_EXTERNO_RECAUDO"),
	ID_UNICO("ID_UNICO"),
	PROPIEDADES("PROPIEDADES"),
	
	//Sede
	EXISTE_SEDE("EXISTE_SEDE"),
	NOMBRE_SEDE("NOMBRE_SEDE"),
	DIRECCION_SEDE("DIRECCION_SEDE"),
	TELEFONO_SEDE("TELEFONO_SEDE"),
	
	//Clave de Seguridad
	EXISTE_CLAVE_SEGURIDAD("EXISTE_CLAVE_SEGURIDAD"),
	CLAVE_SEGURIDAD("CLAVE_SEGURIDAD"),
	
	//Firma biometrica
	EXISTE_FIRMA_BIOMETRICA("EXISTE_FIRMA_BIOMETRICA"),
	FIRMA_BIOMETRICA("FIRMA_BIOMETRICA"),
	
	//Pago Giro Internacional
	PIN_SG("PIN_SG"),
	ACTIVIDADES_LICITAS("ACTIVIDADES_LICITAS"),
	NUMERO_OPERACION("NUMERO_OPERACION"),
	OPERACION("OPERACION"),
	CIUDAD("CIUDAD"),
	OFICINA("OFICINA"),
	IPTERMINAL("IPTERMINAL"),
	CAJERO("CAJERO"),
	FECHA("FECHA"),
	CENTRO_COSTO("CENTRO_COSTO"),
	CONSECUTIVO_FPISA("CONSECUTIVO_FPISA"),
	REFERENCIA_AUXILIAR("REFERENCIA_AUXILIAR"),
	CORRESPONSAL("CORRESPONSAL"),
	COD_CORRESPONSAL("COD_CORRESPONSAL"),
	TIPO_DOC_BENEFICIARIO("TIPO_DOC_BENEFICIARIO"),
	NO_DOC_BENEFICIARIO("NO_DOC_BENEFICIARIO"),
	NOMBRE_BENEFICIARIO("NOMBRE_BENEFICIARIO"),
	TELEFONO("TELEFONO"),
	DIRECCION("DIRECCION"),
	CODIGO_CIUDAD("CODIGO_CIUDAD"),
	NOMBRE_REMITENTE("NOMBRE_REMITENTE"),
	VALOR_PESOS("VALOR_PESOS"),
	VALOR_PESOS_LETRAS("VALOR_PESOS_LETRAS"),
	GMF("GMF"),
	COSTOS("COSTOS"),
	IVA("IVA"),
	FATCA("FATCA"),
	TIPO_CAMBIO_USD("TIPO_CAMBIO_USD"),
	VALOR_TOTAL_USD("VALOR_TOTAL_USD"),
	NUMERAL("NUMERAL"),
	VALOR_EN_USD("VALOR_EN_USD"),
	PAGO_REALIZADO_POR_NOMBRE_BE("PAGO_REALIZADO_POR_NOMBRE_BE"),
	
	//Seguro Internacional
	PIN_SEGURO("PIN_SEGURO"),
	CEDULA_ASEGURADO("CEDULA_ASEGURADO"),
	CEDULA_REMITENTE("CEDULA_REMITENTE"),
	VALOR_ASEGURADO("VALOR_ASEGURADO"),
	LOGIN_CAJERO("LOGIN_CAJERO"),
	
	//SMS internacional
	AGENCIA_ORIGEN("AGENCIA_ORIGEN"),
	TELEFONO_BENEFICIARIO("TELEFONO_BENEFICIARIO"),
	
	//Envio de giro internacional
    PIN_SG_ENV("PIN_SG"),
    ACTIVIDADES_LICITAS_ENV("ACTIVIDADES_LICITAS"),
    NUMERO_OPERACION_ENV("NUMERO_OPERACION"),
    OPERACION_ENV("OPERACION"),
    CIUDAD_ENV("CIUDAD"),
    OFICINA_ENV("OFICINA"),
    IPTERMINAL_ENV("IPTERMINAL"),
    CAJERO_ENV("CAJERO"),
    FECHA_ENV("FECHA"),
    CENTRO_COSTO_ENV("CENTRO_COSTO"),
    CONSECUTIVO_FPISA_ENV("CONSECUTIVO_FPISA"),
    REFERENCIA_AUXILIAR_ENV("REFERENCIA_AUXILIAR"),
    TIPO_DOCUMENTO_REMITENTE("TIPO_DOC_REMITENTE"),
    NUMERO_DOCUMENTO_REMITENTE("NO_DOC_REMITENTE"),
    NOMBRE_RAZON_SOCIAL("NOMBRES_REMITENTE"),
    TELEFONO_ENV("TELEFONO"),
    DIRECCION_ENV("DIRECCION"),
    CODIGO_CIUDAD_ENV("CODIGO_CIUDAD"),
    VALOR_PESOS_ENV("VALOR_PESOS"),
    VALOR_PESOS_LETRAS_ENV("VALOR_PESOS_LETRAS"),    
    GMF_ENV("GMF"),
    COSTOS_ENV("COSTOS"),
    IVA_ENV("IVA"),
    FATCA_ENV("FATCA"),
    CODIGO_MONEDA("CODIGO_MONEDA"),
    VALOR_MONEDA("VALOR_MONEDA"),
    TIPO_CAMBIO_USD_ENV("TIPO_CAMBIO_USD"),
    VALOR_TOTAL_USD_ENV("VALOR_TOTAL_USD"),
    NUMERAL_ENV("NUMERAL"),
    VALOR_EN_USD_ENV("VALOR_EN_USD"),
    CORRESPONSAL_ENV("CORRESPONSAL"),
    NOMBRE_BENEFICIARIO_ENV("NOMBRE_BENEFICIARIO"),
    APELLIDO_BENEFICIARIO_ENV("APELLIDO_BENEFICIARIO"),
    NOMBRES_REMITENTE("NOMBRES_REMITENTE_R"),
    CONSECUTIVO_SG("REFERENCIA"),
	
	//Variables deprecadas utilizadas en principio por la impresion original de CAMBIO_BENEFICIARIO formato inicial
	@Deprecated
	DPR_PIN("PIN"),
	@Deprecated
	DPR_FACTURA_VENTA("FACTURA_VENTA"),
	@Deprecated
	DPR_FECHA_CAMBIO("FECHA_CAMBIO"),
	@Deprecated
	DPR_NOMBRE_OFICINA_ORIGEN("NOMBRE_OFICINA_ORIGEN"),
	@Deprecated
	DPR_NOMBRE_OFICINA_DESTINO("NOMBRE_OFICINA_DESTINO"),
	@Deprecated
	DPR_NOMBRE_TERC_ORIG("NOMBRE_TERC_ORIG"),
	@Deprecated
	DPR_IDENTIFICACION_TERC_ORIG("IDENTIFICACION_TERC_ORIG"),
	@Deprecated
	DPR_DIRECCION_TERC_ORIG("DIRECCION_TERC_ORIG"),
	@Deprecated
	DPR_TELEFONO_TERC_ORIG("TELEFONO_TERC_ORIG"),
	@Deprecated
	DPR_CELULAR_TERC_ORIG("CELULAR_TERC_ORIG"),
	@Deprecated
	DPR_NOMBRE_TERC_DEST("NOMBRE_TERC_DEST"),
	@Deprecated
	DPR_IDENTIFICACION_TERC_DEST("IDENTIFICACION_TERC_DEST"),
	@Deprecated
	DPR_DIRECCION_TERC_DEST("DIRECCION_TERC_DEST"),
	@Deprecated
	DPR_TELEFONO_TERC_DEST("TELEFONO_TERC_DEST"),
	@Deprecated
	DPR_CELULAR_TERC_DEST("CELULAR_TERC_DEST"),
	@Deprecated
	DPR_NOMBRE_TERC_NUEV("NOMBRE_TERC_NUEV"),
	@Deprecated
	DPR_IDENTIFICACION_TERC_NUEV("IDENTIFICACION_TERC_NUEV"),
	@Deprecated
	DPR_DIRECCION_TERC_NUEV("DIRECCION_TERC_NUEV"),
	@Deprecated
	DPR_TELEFONO_TERC_NUEV("TELEFONO_TERC_NUEV"),
	@Deprecated
	DPR_CELULAR_TERC_NUEV("CELULAR_TERC_NUEV"),
	@Deprecated
	DPR_TELEFONO_EMPRESACB("TELEFONO"),
	@Deprecated
	DPR_NOMBRE_PERSONA("NOMBRE_PERSONA"),
	@Deprecated
	DPR_MONTO_ENVIADO("MONTO_ENVIADO"),
	@Deprecated
	DPR_MONTO_RECIBIDO("MONTO_RECIBIDO"),
	;
	
	private final String nombre;
	
	private EnumVariablesImpresion(String nombre){
		this.nombre=nombre;
	}

	public String getNombre() {
		return nombre;
	}
	
}
